//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinzoe_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodSet()
        {
            this.FoodDetailSet = new HashSet<FoodDetailSet>();
            this.PickedItemSet = new HashSet<PickedItemSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int FoodCategory_Id { get; set; }
    
        public virtual FoodCategorySet FoodCategorySet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodDetailSet> FoodDetailSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickedItemSet> PickedItemSet { get; set; }
    }
}
