//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinzoe_Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSet_Giftbox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSet_Giftbox()
        {
            this.GiftboxItemSet = new HashSet<GiftboxItemSet>();
        }
    
        public int Id { get; set; }
        public int GiftboxType_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftboxItemSet> GiftboxItemSet { get; set; }
        public virtual GiftboxTypeSet GiftboxTypeSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
